from pprint import pp
import re, os

# sets working directory to current folder
os.chdir(os.path.dirname(os.path.abspath(__file__)))

TEST_DATA = [
    {
        "Gen": 8,
        "Species": [
            {
                "ID": 869,
                "Species": "Alcremie",
                "Forms": [
                    {
                        "Name": "Vanilla Cream Strawberry Sweet",
                        "Image": "0869_000_0_Alcremie_Vanilla_Cream_Strawberry_Sweet",
                        "Shiny": "0869_000_0_Alcremie_Strawberry_Sweet",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Ruby Cream Strawberry Sweet",
                        "Image": "0869_001_0_Alcremie_Ruby_Cream_Strawberry_Sweet",
                        "Shiny": "0869_000_0_Alcremie_Strawberry_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Matcha Cream Strawberry Sweet",
                        "Image": "0869_002_0_Alcremie_Matcha_Cream_Strawberry_Sweet",
                        "Shiny": "0869_000_0_Alcremie_Strawberry_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Mint Cream Strawberry Sweet",
                        "Image": "0869_003_0_Alcremie_Mint_Cream_Strawberry_Sweet",
                        "Shiny": "0869_000_0_Alcremie_Strawberry_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Lemon Cream Strawberry Sweet",
                        "Image": "0869_004_0_Alcremie_Lemon_Cream_Strawberry_Sweet",
                        "Shiny": "0869_000_0_Alcremie_Strawberry_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Salted Cream Strawberry Sweet",
                        "Image": "0869_005_0_Alcremie_Salted_Cream_Strawberry_Sweet",
                        "Shiny": "0869_000_0_Alcremie_Strawberry_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Ruby Swirl Strawberry Sweet",
                        "Image": "0869_006_0_Alcremie_Ruby_Swirl_Strawberry_Sweet",
                        "Shiny": "0869_000_0_Alcremie_Strawberry_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Caramel Swirl Strawberry Sweet",
                        "Image": "0869_007_0_Alcremie_Caramel_Swirl_Strawberry_Sweet",
                        "Shiny": "0869_000_0_Alcremie_Strawberry_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Rainbow Swirl Strawberry Sweet",
                        "Image": "0869_008_0_Alcremie_Rainbow_Swirl_Strawberry_Sweet",
                        "Shiny": "0869_000_0_Alcremie_Strawberry_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Vanilla Cream Berry Sweet",
                        "Image": "0869_000_1_Alcremie_Vanilla_Cream_Berry_Sweet",
                        "Shiny": "0869_000_1_Alcremie_Berry_Sweet",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Ruby Cream Berry Sweet",
                        "Image": "0869_001_1_Alcremie_Ruby_Cream_Berry_Sweet",
                        "Shiny": "0869_000_1_Alcremie_Berry_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Matcha Cream Berry Sweet",
                        "Image": "0869_002_1_Alcremie_Matcha_Cream_Berry_Sweet",
                        "Shiny": "0869_000_1_Alcremie_Berry_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Mint Cream Berry Sweet",
                        "Image": "0869_003_1_Alcremie_Mint_Cream_Berry_Sweet",
                        "Shiny": "0869_000_1_Alcremie_Berry_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Lemon Cream Berry Sweet",
                        "Image": "0869_004_1_Alcremie_Lemon_Cream_Berry_Sweet",
                        "Shiny": "0869_000_1_Alcremie_Berry_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Salted Cream Berry Sweet",
                        "Image": "0869_005_1_Alcremie_Salted_Cream_Berry_Sweet",
                        "Shiny": "0869_000_1_Alcremie_Berry_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Ruby Swirl Berry Sweet",
                        "Image": "0869_006_1_Alcremie_Ruby_Swirl_Berry_Sweet",
                        "Shiny": "0869_000_1_Alcremie_Berry_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Caramel Swirl Berry Sweet",
                        "Image": "0869_007_1_Alcremie_Caramel_Swirl_Berry_Sweet",
                        "Shiny": "0869_000_1_Alcremie_Berry_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Rainbow Swirl Berry Sweet",
                        "Image": "0869_008_1_Alcremie_Rainbow_Swirl_Berry_Sweet",
                        "Shiny": "0869_000_1_Alcremie_Berry_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Vanilla Cream Love Sweet",
                        "Image": "0869_000_2_Alcremie_Vanilla_Cream_Love_Sweet",
                        "Shiny": "0869_000_2_Alcremie_Love_Sweet",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Ruby Cream Love Sweet",
                        "Image": "0869_001_2_Alcremie_Ruby_Cream_Love_Sweet",
                        "Shiny": "0869_000_2_Alcremie_Love_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Matcha Cream Love Sweet",
                        "Image": "0869_002_2_Alcremie_Matcha_Cream_Love_Sweet",
                        "Shiny": "0869_000_2_Alcremie_Love_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Mint Cream Love Sweet",
                        "Image": "0869_003_2_Alcremie_Mint_Cream_Love_Sweet",
                        "Shiny": "0869_000_2_Alcremie_Love_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Lemon Cream Love Sweet",
                        "Image": "0869_004_2_Alcremie_Lemon_Cream_Love_Sweet",
                        "Shiny": "0869_000_2_Alcremie_Love_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Salted Cream Love Sweet",
                        "Image": "0869_005_2_Alcremie_Salted_Cream_Love_Sweet",
                        "Shiny": "0869_000_2_Alcremie_Love_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Ruby Swirl Love Sweet",
                        "Image": "0869_006_2_Alcremie_Ruby_Swirl_Love_Sweet",
                        "Shiny": "0869_000_2_Alcremie_Love_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Caramel Swirl Love Sweet",
                        "Image": "0869_007_2_Alcremie_Caramel_Swirl_Love_Sweet",
                        "Shiny": "0869_000_2_Alcremie_Love_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Rainbow Swirl Love Sweet",
                        "Image": "0869_008_2_Alcremie_Rainbow_Swirl_Love_Sweet",
                        "Shiny": "0869_000_2_Alcremie_Love_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Vanilla Cream Star Sweet",
                        "Image": "0869_000_3_Alcremie_Vanilla_Cream_Star_Sweet",
                        "Shiny": "0869_000_3_Alcremie_Star_Sweet",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Ruby Cream Star Sweet",
                        "Image": "0869_001_3_Alcremie_Ruby_Cream_Star_Sweet",
                        "Shiny": "0869_000_3_Alcremie_Star_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Matcha Cream Star Sweet",
                        "Image": "0869_002_3_Alcremie_Matcha_Cream_Star_Sweet",
                        "Shiny": "0869_000_3_Alcremie_Star_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Mint Cream Star Sweet",
                        "Image": "0869_003_3_Alcremie_Mint_Cream_Star_Sweet",
                        "Shiny": "0869_000_3_Alcremie_Star_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Lemon Cream Star Sweet",
                        "Image": "0869_004_3_Alcremie_Lemon_Cream_Star_Sweet",
                        "Shiny": "0869_000_3_Alcremie_Star_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Salted Cream Star Sweet",
                        "Image": "0869_005_3_Alcremie_Salted_Cream_Star_Sweet",
                        "Shiny": "0869_000_3_Alcremie_Star_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Ruby Swirl Star Sweet",
                        "Image": "0869_006_3_Alcremie_Ruby_Swirl_Star_Sweet",
                        "Shiny": "0869_000_3_Alcremie_Star_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Caramel Swirl Star Sweet",
                        "Image": "0869_007_3_Alcremie_Caramel_Swirl_Star_Sweet",
                        "Shiny": "0869_000_3_Alcremie_Star_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Rainbow Swirl Star Sweet",
                        "Image": "0869_008_3_Alcremie_Rainbow_Swirl_Star_Sweet",
                        "Shiny": "0869_000_3_Alcremie_Star_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Vanilla Cream Clover Sweet",
                        "Image": "0869_000_4_Alcremie_Vanilla_Cream_Clover_Sweet",
                        "Shiny": "0869_000_4_Alcremie_Clover_Sweet",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Ruby Cream Clover Sweet",
                        "Image": "0869_001_4_Alcremie_Ruby_Cream_Clover_Sweet",
                        "Shiny": "0869_000_4_Alcremie_Clover_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Matcha Cream Clover Sweet",
                        "Image": "0869_002_4_Alcremie_Matcha_Cream_Clover_Sweet",
                        "Shiny": "0869_000_4_Alcremie_Clover_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Mint Cream Clover Sweet",
                        "Image": "0869_003_4_Alcremie_Mint_Cream_Clover_Sweet",
                        "Shiny": "0869_000_4_Alcremie_Clover_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Lemon Cream Clover Sweet",
                        "Image": "0869_004_4_Alcremie_Lemon_Cream_Clover_Sweet",
                        "Shiny": "0869_000_4_Alcremie_Clover_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Salted Cream Clover Sweet",
                        "Image": "0869_005_4_Alcremie_Salted_Cream_Clover_Sweet",
                        "Shiny": "0869_000_4_Alcremie_Clover_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Ruby Swirl Clover Sweet",
                        "Image": "0869_006_4_Alcremie_Ruby_Swirl_Clover_Sweet",
                        "Shiny": "0869_000_4_Alcremie_Clover_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Caramel Swirl Clover Sweet",
                        "Image": "0869_007_4_Alcremie_Caramel_Swirl_Clover_Sweet",
                        "Shiny": "0869_000_4_Alcremie_Clover_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Rainbow Swirl Clover Sweet",
                        "Image": "0869_008_4_Alcremie_Rainbow_Swirl_Clover_Sweet",
                        "Shiny": "0869_000_4_Alcremie_Clover_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Vanilla Cream Flower Sweet",
                        "Image": "0869_000_5_Alcremie_Vanilla_Cream_Flower_Sweet",
                        "Shiny": "0869_000_5_Alcremie_Flower_Sweet",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Ruby Cream Flower Sweet",
                        "Image": "0869_001_5_Alcremie_Ruby_Cream_Flower_Sweet",
                        "Shiny": "0869_000_5_Alcremie_Flower_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Matcha Cream Flower Sweet",
                        "Image": "0869_002_5_Alcremie_Matcha_Cream_Flower_Sweet",
                        "Shiny": "0869_000_5_Alcremie_Flower_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Mint Cream Flower Sweet",
                        "Image": "0869_003_5_Alcremie_Mint_Cream_Flower_Sweet",
                        "Shiny": "0869_000_5_Alcremie_Flower_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Lemon Cream Flower Sweet",
                        "Image": "0869_004_5_Alcremie_Lemon_Cream_Flower_Sweet",
                        "Shiny": "0869_000_5_Alcremie_Flower_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Salted Cream Flower Sweet",
                        "Image": "0869_005_5_Alcremie_Salted_Cream_Flower_Sweet",
                        "Shiny": "0869_000_5_Alcremie_Flower_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Ruby Swirl Flower Sweet",
                        "Image": "0869_006_5_Alcremie_Ruby_Swirl_Flower_Sweet",
                        "Shiny": "0869_000_5_Alcremie_Flower_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Caramel Swirl Flower Sweet",
                        "Image": "0869_007_5_Alcremie_Caramel_Swirl_Flower_Sweet",
                        "Shiny": "0869_000_5_Alcremie_Flower_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Rainbow Swirl Flower Sweet",
                        "Image": "0869_008_5_Alcremie_Rainbow_Swirl_Flower_Sweet",
                        "Shiny": "0869_000_5_Alcremie_Flower_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Vanilla Cream Ribbon Sweet",
                        "Image": "0869_000_6_Alcremie_Vanilla_Cream_Ribbon_Sweet",
                        "Shiny": "0869_000_6_Alcremie_Ribbon_Sweet",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Ruby Cream Ribbon Sweet",
                        "Image": "0869_001_6_Alcremie_Ruby_Cream_Ribbon_Sweet",
                        "Shiny": "0869_000_6_Alcremie_Ribbon_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Matcha Cream Ribbon Sweet",
                        "Image": "0869_002_6_Alcremie_Matcha_Cream_Ribbon_Sweet",
                        "Shiny": "0869_000_6_Alcremie_Ribbon_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Mint Cream Ribbon Sweet",
                        "Image": "0869_003_6_Alcremie_Mint_Cream_Ribbon_Sweet",
                        "Shiny": "0869_000_6_Alcremie_Ribbon_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Lemon Cream Ribbon Sweet",
                        "Image": "0869_004_6_Alcremie_Lemon_Cream_Ribbon_Sweet",
                        "Shiny": "0869_000_6_Alcremie_Ribbon_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Salted Cream Ribbon Sweet",
                        "Image": "0869_005_6_Alcremie_Salted_Cream_Ribbon_Sweet",
                        "Shiny": "0869_000_6_Alcremie_Ribbon_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Ruby Swirl Ribbon Sweet",
                        "Image": "0869_006_6_Alcremie_Ruby_Swirl_Ribbon_Sweet",
                        "Shiny": "0869_000_6_Alcremie_Ribbon_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Caramel Swirl Ribbon Sweet",
                        "Image": "0869_007_6_Alcremie_Caramel_Swirl_Ribbon_Sweet",
                        "Shiny": "0869_000_6_Alcremie_Ribbon_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Rainbow Swirl Ribbon Sweet",
                        "Image": "0869_008_6_Alcremie_Rainbow_Swirl_Ribbon_Sweet",
                        "Shiny": "0869_000_6_Alcremie_Ribbon_Sweet.png",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                    },
                    {
                        "Name": "Gigantamax",
                        "Image": "0869_000_G_Alcremie_Gigantamax",
                        "Shiny": "0869_000_G_Alcremie_Gigantamax",
                        "Gen": 8,
                        "Type A": "Fairy",
                        "Type B": None,
                        "HP": 65,
                        "Atk": 60,
                        "Def": 75,
                        "SpA": 110,
                        "SpD": 121,
                        "Spe": 64,
                        "BST": 495,
                        "Gmax": True,
                    },
                ],
            },
        ],
    }
]

SCROLL_WRAPPER_TEMPLATE = '<div class="scroll-wrapper" tabindex="-1">\n{}\n</div>'
GROUP_TEMPLATE = '<div id="{id}" class="item-group hide">\n{buttons}\n</div>'
DATA_TEMPLATE = 'data-{key}="{value}"'
BUTTON_TEMPLATE = (
    '<button class="item hide" {data} aria-label="select item">\n{img}\n</button>'
)
NORMAL_IMG = "images/pokemon/normal/{}.png"
SHINY_IMG = "images/pokemon/shiny/{}.png"
IMG_TEMPLATE = '<img src="{}" loading="lazy">'

ATTRIBUTES_TO_SKIP = ["Name", "Image", "Shiny"]

itemGroups = []
nationalButtons = []


def processForm(speciesName, form, formName=None, includeData=True):
    attributes = [DATA_TEMPLATE.format(key="name", value=formName if formName else form["Name"])]

    if includeData:
        attributes.append(DATA_TEMPLATE.format(key="species", value=speciesName))
        attributes += [
            DATA_TEMPLATE.format(key=key.replace(" ", "-").replace(".", "").lower(), value=form[key])
            for key in form
            if form[key] and key not in ATTRIBUTES_TO_SKIP
        ]
        if form["Shiny"]:
            attributes.append(
                DATA_TEMPLATE.format(key="shiny", value=SHINY_IMG.format(form["Shiny"]))
            )

    return BUTTON_TEMPLATE.format(
        data=" ".join(attributes),
        img=IMG_TEMPLATE.format(NORMAL_IMG.format(form["Image"])),
    )


def processAlcremie(speciesName, forms):
    mainGroupButtons = []
    creamGroups = []

    for cream in forms[:9]:
        formName = cream["Name"]
        spaceIterator = re.finditer(" ", formName)
        next(spaceIterator)
        middleSpaceIndex = next(spaceIterator).start()
        creamName = formName[:middleSpaceIndex].strip()

        mainGroupButtons.append(processForm(speciesName, cream, creamName))

        creamButtons = []

        for candy in forms[forms.index(cream) :: 9]:
            if "Gmax" in candy:
                continue

            formName = candy["Name"]
            candyName = formName[middleSpaceIndex:].strip()

            creamButtons.append(processForm(speciesName, candy, candyName))

        creamGroups.append(
            GROUP_TEMPLATE.format(
                id=creamName.replace(" ", "-"), buttons="\n".join(creamButtons)
            )
        )

    # processes Gmax
    mainGroupButtons.append(processForm(speciesName, forms[-1]))

    itemGroups.append(
        GROUP_TEMPLATE.format(
            id=speciesName.replace(" ", "-"), buttons="\n".join(mainGroupButtons)
        )
    )
    itemGroups.extend(creamGroups)


def processSpecies(species):
    speciesName = species["Species"]
    forms = species["Forms"]

    if species["ID"] == 869:
        processAlcremie(speciesName, forms)
        return

    if len(forms) > 1:
        buttons = [processForm(speciesName, form) for form in forms]
        itemGroups.append(
            GROUP_TEMPLATE.format(
                id=speciesName.replace(" ", "-"), buttons="\n".join(buttons)
            )
        )
    
    nationalButtons.append(processForm(speciesName, forms[0], speciesName, len(forms) == 1))


def run(allData):
    for gen in allData:
        for species in gen["Species"]:
            processSpecies(species)

    itemGroups.insert(
        0, GROUP_TEMPLATE.format(id="National", buttons="\n".join(nationalButtons))
    )

    with open(os.path.join(os.getcwd(), "output.html"), "w") as file:
        file.write(SCROLL_WRAPPER_TEMPLATE.format("\n".join(itemGroups)))
        file.close()


if __name__ == "__main__":
    run(TEST_DATA)
